// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.jslee.rockredis.grpc;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
