// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.jslee.rockredis.grpc;

public interface GetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
