// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.jslee.rockredis.grpc;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_SetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_SetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_SetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_SetReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_GetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_GetReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\006server\"(\n\nSetRequest\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\n\n\010SetReply\"\031\n\n" +
      "GetRequest\022\013\n\003key\030\001 \001(\t\"\031\n\010GetReply\022\r\n\005v" +
      "alue\030\001 \001(\t2j\n\nRockServer\022-\n\003Set\022\022.server" +
      ".SetRequest\032\020.server.SetReply\"\000\022-\n\003Get\022\022" +
      ".server.GetRequest\032\020.server.GetReply\"\000B)" +
      "\n\030com.jslee.rockredis.grpcB\013ServerProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_SetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_SetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_SetRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_server_SetReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_SetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_SetReply_descriptor,
        new java.lang.String[] { });
    internal_static_server_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_server_GetReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_server_GetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_GetReply_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
