// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.jslee.rockredis.grpc;

public interface SetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.SetReply)
    com.google.protobuf.MessageOrBuilder {
}
