// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.jslee.rockredis.grpc;

public interface SetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.SetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
